version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
  app:
    ports:
        - 80:80
        - 40000:40000
    build:
      dockerfile: ./build/Dockerfile
      context: ..
    volumes:
      - ../log:/log
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'