version: '3'

services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
  integration_tests:
    build:
      dockerfile: ./build/calendar_test/Dockerfile
      context: ..
    depends_on:
      - postgres
    volumes:
      - ../log:/log