version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
  calendar:
    depends_on:
      - postgres
    build:
      dockerfile: ./build/calendar/Dockerfile
      context: ..
    volumes:
      - ../log:/log
  integration_tests:
    build:
      dockerfile: ./build/calendar_test/Dockerfile
      context: ..
    depends_on:
      - postgres
      - calendar