server:
  http:
    host: "localhost"
    port: "80"
  grpc:
    host: "localhost"
    port: "40000"

logger:
  path: "/log/log.txt"
  level: "debug"

db:
  postgres:
    dialect: "postgres"
    dsn: "host=localhost port=5401 dbname=postgres user=postgres password=postgres sslmode=disable"
  memory:
    maxsize: 20

repository:
  type: "memory"

