server:
  http:
    host: "app"
    port: "80"

db:
  postgres:
    dialect: "postgres"
    dsn: "host=postgres port=5432 dbname=db user=db password=db sslmode=disable"
  memory:
    maxsize: 20

repository:
  type: "postgres"